In [4]:
import pandas as pd

In [17]:
# read csvs
import pandas as pd

crime = pd.read_csv(
    "chicago_crimes.csv",
    on_bad_lines="skip",
    engine="python"
)

print(crime.shape)
service = pd.read_csv(
    "chicago_311.csv",
    on_bad_lines="skip",
    engine="python"
)

print(service.shape)

(111332, 22)
(906957, 8)

In [29]:
# check columns and filter
crime = crime[['Date', 'Primary Type']]
service = service[['CREATED_DATE', 'SR_TYPE']]

In [31]:
crime.head()

                     Date Primary Type
0  04/28/2026 12:00:00 AM      BATTERY
1  04/28/2026 12:00:00 AM      ASSAULT
2  04/28/2026 12:00:00 AM     BURGLARY
3  04/28/2026 12:00:00 AM      ASSAULT
4  04/28/2026 12:00:00 AM        THEFT

In [32]:
service.head()

             CREATED_DATE                         SR_TYPE
0  05/06/2025 02:56:23 PM        Graffiti Removal Request
1  05/06/2025 02:56:27 PM  City Vehicle Sticker Violation
2  05/06/2025 02:56:27 PM       311 INFORMATION ONLY CALL
3  05/06/2025 02:56:28 PM           Fly Dumping Complaint
4  05/06/2025 02:56:33 PM        Aircraft Noise Complaint

In [42]:
# rename columns
crime = crime.rename(columns = {
    'Primary Type': 'category'
})
service = service.rename(columns = {
   'CREATED_DATE': 'Date',
    'SR_TYPE': 'category'
})

In [34]:
# convert datetimes 
crime['Date'] = pd.to_datetime(crime['Date'], errors='coerce')
service['Date'] = pd.to_datetime(service['Date'], errors='coerce')

/tmp/ipykernel_194/290519679.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  crime['Date'] = pd.to_datetime(crime['Date'], errors='coerce')
/tmp/ipykernel_194/290519679.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  service['Date'] = pd.to_datetime(service['Date'], errors='coerce')

In [43]:
# Drop missing values
crime = crime.dropna(subset=['Date', 'category'])
service = service.dropna(subset=['Date', 'category'])

In [44]:
crime['month'] = crime['Date'].dt.to_period('M')
service['month'] = service['Date'].dt.to_period('M')

In [49]:
crime.to_csv("crime_clean.csv", index=False)
service.to_csv("service_clean.csv", index=False)

print("Saved processed datasets.")

Saved processed datasets.